### ISSUE TITLE
Set variables as immutable

### ISSUE THREAD

**Issue by pyk** [jpvge/advisor-vesting-contracts#1]
We can set these as `immutable`

https://github.com/brritoxyz/advisor-vesting-contracts/blob/82ff287189d6540b262ec14f447b6fa06e5053bc/src/AdvisorVestingWallet.sol#L19-L32

**Comment by kphed** [comment]
Besides parametrizing them (which we don't want to do for these contracts), is there another reason for setting them to `immutable`?

**Comment by kphed** [comment]
Actually, after thinking about it further, we may bring on advisors in the future. I guess I can make those changes in the future - will leave this issue open - since they're not a priority atm.
