### ISSUE TITLE
Remove unnecessary overrides

### ISSUE THREAD

**Issue by pyk** [jpvge/advisor-vesting-contracts#3]
https://github.com/brritoxyz/advisor-vesting-contracts/blob/82ff287189d6540b262ec14f447b6fa06e5053bc/src/AdvisorVestingWallet.sol#L59-L69

[VestingWallet](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/fd81a96f01cc42ef1c9a5399364968d0e07e9e90/contracts/finance/VestingWallet.sol) will do nothing if there is no ETH streamed to the beneficiary.

As an alternative, u can override `receive` function and revert if ETH is transfered to the vesting contract.

```
receive() external payable override {
    revert NoETH();
}
```

**Comment by kphed** [comment]
Here are a few reasons why I'm doing this:
- The bytecode is reduced by ~10%.
- There's no foolproof way to prevent inbound ETH transfers for the contract.
- It's a simple solution.

Would love to hear your thoughts if any.
