### ISSUE TITLE
Simplify `withdrawUnvested`

### ISSUE THREAD

**Issue by pyk** [jpvge/advisor-vesting-contracts#4]
https://github.com/brritoxyz/advisor-vesting-contracts/blob/82ff287189d6540b262ec14f447b6fa06e5053bc/src/AdvisorVestingWallet.sol#L48-L57

we can simply call `release(TOKEN)` then transfer remaining balance to owner

```solidity
function withdrawUnvested() external onlyOwner { 
     release(TOKEN);
     TOKEN.safeTransfer(owner(), TOKEN.balanceOf(address(this))); 
 } 
```

The `finalReleasedAmount` is already emitted in this event:

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/fd81a96f01cc42ef1c9a5399364968d0e07e9e90/contracts/finance/VestingWallet.sol#L111-L116

**Comment by kphed** [comment]
Thanks for that @pyk , that's much cleaner than what I have now 👑 - going to implement it.
